language: rust
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo +nightly install rustfmt-nightly
script:
  - cargo +nightly fmt -- --write-mode=diff
  - cargo +nightly build
  - cargo +nightly test
