language: rust
rust: nightly-2018-04-14
branches:
  only:
    - master
    - /^v[0-9]/
cache:
  cargo: true
  timeout: 1000
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --features clippy
  - cargo test
  - cargo build --release
  - strip target/release/jsssa
  - ls -lh target/release
deploy:
  - provider: releases
    api_key:
      secure: H2lo/GPCQOTfawJeo6B88RivC7yH129OEQez+hM/feVC6Z4KCZBKqpaVtuAplQnocjhJVRxSmut3hbhlh3BMuE9ERYtnan6nKM76O88YK+v01IYklrwCYNeh8N5p9RXTCKJvD2sjTfKEZLxrhnfZSOdY4XDBnJg4UZ7JyBOBW37DOyrB/H8FhWZsNm7PbgOyBgxLIQYS80cPU+t96onvGDGn1E/w2iC4Yc7YeHaDt/1kH2t7ObBjZ1ZUTutsPFYYXUY7rcUy7/843NbMuxP6+5iZdB1clODaMXN03mzFP4YfgtcTKgotODZZUff72uNqVvYph0PIkARvBWeyrkV0mgv+hoRGkm98uGRsk+9iUd5SyFNK9GFtBbuauKc56NwcrogCnQAJu1UdUXPtrtn+ZANG9VRHaGN8wy7ANdX2iLog4N1heoI7ZcS6Q0ivd8i54HshkyNjJJKQhpyrS6+30HZR3YjOeTU6m3eQxISXO1nzqPlFAqM2HE7xMcv17omhkhJjussaqqF+YDGMspI7z8xs0HQZrCDBTXkRpavsHQFyFIRVo8vy7eo2QiuGxDnvf7j/ZXNklP/8DrntcrpKxj15+ANh/nCH4P/tsRJ8h6k6qQANPlOIY1GOxPAArDaCd+JntxEHDYuOQdtV9nhwBo01wZK2b6UnEjM+95B+aUc=
    file: target/release/jsssa
    skip_cleanup: true
    on:
      tags: true
