language: rust
cache: cargo
before_script:
  - rustup default nightly
  - cargo install --force rustfmt-nightly
script:
  - cargo fmt -- --write-mode=diff
  - cargo test
  - cargo build --release --features clippy && strip target/release/jsssa
  - ls -lh target/release
