language: rust
cache: cargo
before_script:
  - rustup default nightly
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --write-mode=diff
  - cargo test
  - cargo build --release --features clippy
  - strip target/release/jsssa
  - ls -lh target/release
