[package]
name = "jsssa"
version = "0.0.0"

[dependencies]
clippy = "*"
failure = "0.1"
failure_derive = "0.1"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[profile.release]
lto = true
