[package]
name = "jsssa"
version = "0.0.0"
description = "JS optimizer with SSA-based IR"
edition = "2018"

[dependencies]
env_logger = { version = "0.6", default-features = false }
log = "0.4"
structopt = { version = "0.2", default-features = false }
swc_atoms = "0.1"
swc_common = "0.3"
swc_ecma_ast = "0.8"
swc_ecma_codegen = "0.6"
swc_ecma_parser = "0.9"
swc_fixer = { path = "./swc_fixer" }

[dev-dependencies]
insta = "0.7"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
debug = true
