[package]
name = "jsssa"
version = "0.0.0"
description = "JS optimizer with SSA-based IR"
edition = "2018"

[dependencies]
env_logger = { version = "0.7", default-features = false }
log = "0.4"
structopt = { version = "0.3", default-features = false }
swc_atoms = "0.2"
swc_common = "0.4"
swc_ecma_ast = "0.15"
swc_ecma_codegen = "0.14"
swc_ecma_parser = "0.17"
swc_ecma_transforms = "0.6"

[dev-dependencies]
insta = "0.12"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
debug = true
