[package]
name = "jsssa"
version = "0.0.0"
edition = "2018"

[dependencies]
failure = "0.1"
if_chain = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
swc_atoms = "0.1"
swc_common = "0.2"
swc_ecma_ast = "0.7"
swc_ecma_parser = "0.8"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
