[package]
name = "jsssa"
version = "0.0.0"

[dependencies]
clippy = { version = "*", optional = true }
failure = "0.1"
failure_derive = "0.1"
mozjs = { version = "0.6", default-features = false }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[profile.release]
panic = "abort"
debug = false
lto = true
codegen-units = 1
